language: node_js
node_js:
  - "8"
  - "10"
services: docker
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install
  - yarn setup
install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images
  - if [ "$TRAVIS_OS_NAME" = 'linux' ]; then wget -qO- 'https://github.com/tianon/pgp-happy-eyeballs/raw/master/hack-my-builds.sh' | bash; fi
before_script:
  - env | sort
  - cd "$VERSION${VARIANT:+/$VARIANT}"
  - image="mongo:$VERSION${VARIANT:+$(basename "$VARIANT")}"
script:
  - |
    docker build -t "$image" .
    docker run --rm "$image" mongod --version
    docker run --rm "$image" mongo --version
after_script:
  - docker images