language: node_js
node_js:
  - "10"
services:
  - mongodb
before_script:
  - mongo rpg_dev_db_test --eval 'db.createUser({user:"travis",pwd:"test",roles:["readWrite"]});'
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install
  - yarn setup