sudo: required

language: node_js

node_js:
  - 12

env:
  matrix:
    - MONGODB=4.0

services:
  - docker

before_script:
  - docker run -d -p 27017:27017 mongo:$MONGODB
  - docker ps -a

script:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH="$HOME/.yarn/bin:$PATH"
  - yarn install
  - yarn setup
  - yarn test